habilidades-motoras/config/routes.rb
Rails.application.routes.draw do
  resources :suggested_posts
  resources :publications
  resources :progresses
  resources :images
  resources :videos
  resources :users
  resources :tips

end

habilidades-motoras/app/models/tip.rb
class Tip < ActiveRecord::Base
    validates :tip_id, presence: true, numericality: true, uniqueness: true
    validates :description, length:{maximun:500}
end

habilidades-motoras/app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:tip_id, :description)
    end
end

habilidades-motoras/app/helpers/tips_helper.rb
module TipsHelper
end

habilidades-motoras/app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tip_id %><br>
    <%= f.number_field :tip_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

habilidades-motoras/app/views/tips/edit.html.erb
<h1>Editing Tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

habilidades-motoras/app/views/tips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tips</h1>

<table>
  <thead>
    <tr>
      <th>Tip</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= tip.tip_id %></td>
        <td><%= tip.description %></td>
        <td><%= link_to 'Show', tip %></td>
        <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
        <td><%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip', new_tip_path %>

habilidades-motoras/app/views/tips/new.html.erb
<h1>New Tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

habilidades-motoras/app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tip:</strong>
  <%= @tip.tip_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tip.description %>
</p>

<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>